# Generated by Django 5.1.2 on 2024-10-22 18:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workstamp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workstamp",
            old_name="employee",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="workstamp",
            name="activities",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workstamp",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
